check return

diff --git a/tools/genall b/tools/genall
--- a/tools/genall
+++ b/tools/genall
@@ -10,23 +10,28 @@ if [ -z "$1" ];then
 fi
 echo "@@ Generating package $pkg file list ..." >&2
 ./tools/genlistall.sh $1> list.$out
+[ $? -ne 0 ] && exit 1
 ./tools/gen_init_cpio list.$out >$out.cpio 
 [ $? -ne 0 ] && ( echo "gen_init_cpio list.$out fail!" >&2 ) && exit 1
 echo "@@ Checking package $pkg cpio ..." >&2
 ./tools/checkcpio $out.cpio >&2
+[ $? -ne 0 ] && exit 1
 
 [ ! -z "$1" ] && ( echo "@@ Generate $pkg done" >&2 ) && exit 0
 #finanal round
 echo "@@ Check package $pkg lib depdence ..." >&2
 ./tools/checkdep initramfs >&2
-[ $? -ne 0 ] && exit
+[ $? -ne 0 ] && exit 1
 ./tools/checkdep initramfs >&2
-[ $? -ne 0 ] && exit
+[ $? -ne 0 ] && exit 1
 echo "@@ Appending package $pkg lib list ..." >&2
 ./tools/getdir $PWD/deplibs/ |tee list.libs >> list.$out
 ./tools/gen_init_cpio list.libs >libs.cpio
+[ $? -ne 0 ] && ( echo "gen_init_cpio list.libs fail!" >&2 ) && exit 1
 chroot $PWD/initramfs/ ldconfig >&2
 [ -z $1 ] && echo "$pkg" >initramfs/rootpkg
 ./tools/getdir $PWD/initramfs/ > list.real.$out
 echo "@@ Generate final $pkg cpio archive ..." >&2
 ./tools/gen_init_cpio list.real.$out >$out.cpio
+[ $? -ne 0 ] && ( echo "gen_init_cpio list.real.$out fail!" >&2 ) && exit 1
+exit 0
